seed: 42
data_dir: Data/
num_workers: 4
num_classes: 100
weight_decay: 0.0001
beta_start: 0.0002
beta_end: 0.02
beta_schedule: linear

variance_type: fixed_small
predictor_type: epsilon
unet_in_ch: 3
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.0

use_CIFAR: False
run_name: ddpm
batch_size: 32
image_size: 64
unet_in_size: 64
unet_ch: 128
num_train_timesteps: 128
num_inference_steps: 128
learning_rate: 2e-4
num_epochs: 16
