DEBUG: False
wandb_key: b6dff554fc854aea97af8dccb735c241a19a6615
project_name: dl-hw5
run_name: test

seed: 42
dataset: cifar10 #test
data_dir: ./data
subset: 0.01
image_size: 128
# batch_size: #BATCH_SIZE 
num_workers: 4 #NUM_WORKERS
# num_classes: #NUM_CLASSES
num_epochs: 100 #NUM_EPOCHS
learning_rate: 5e-5 #LR
# weight_decay: #WD
num_train_timesteps: 500 #TRAINING_TIMESTEPS
num_inference_steps: 500 #INFERENCE_TIMESTEPS
# beta_start: #BETA START
# beta_end: #BETA END
# beta_schedule: #BETA SCHEDULE

variance_type: fixed_small
predictor_type: epsilon
unet_in_size: 128
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.0